[tox]
envlist = py310,py311
isolated_build = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: skip
    3.13: skip

[testenv]
commands = pytest --cov=acld --cov-append --cov-report=term-missing 
deps =
    -rrequirements_dev.txt



